services:
  - type: web
    name: feedback-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: your-render-db-url
      - key: SECRET_KEY
        value: your-secret-key
